spring:
  application:
    name : item-service
  datasource:
    url: jdbc:postgresql://localhost:5436/itemservice_db
    username: itemservice
    password: secret
server:
  port: 0
jwt:
  secret: 1714b351f0c4a3a209c7a5f6188006eb